name       : xorg-driver-video-mach64
version    : 6.9.6
release    : 11
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-mach64-6.9.6.tar.gz : 873a9d64c7d08ca1617d98e9dd58389b948f92c052d7914922d9eed4acb2f6a4
license    : MIT
component  : xorg.driver
summary    : Mach64 Video Driver
description: |
    The Xorg Mach64 Driver package contains the X.Org Video Driver for ATI video adapters based on the Mach64 chipsets.
optimize   :
    - no-symbolic
    - no-bind-now
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(xorg-macros)
    - pkgconfig(xorg-server)
    - pkgconfig(xproto)
enviornment: |
    export CFLAGS="${CFLAGS} -fno-common"
    export CXXFLAGS="${CXXFLAGS} -fno-common"
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
