name       : xorg-driver-video-mach64
version    : 6.9.5
release    : 4
source     :
    - https://www.x.org/archive/individual/driver/xf86-video-mach64-6.9.5.tar.bz2 : 3e98985b6e044189efd42342862208f472881c25debf22230a1d54a96d71b41f
license    : MIT
component  : xorg.driver
optimize   :
    - no-bind-now
    - no-symbolic
summary    : Mach64 Video Driver
builddeps  :
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
    - pkgconfig(xorg-macros)
    - pkgconfig(xorg-server)
description: |
    The Xorg Mach64 Driver package contains the X.Org Video Driver for ATI video adapters based on the Mach64 chipsets.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
